---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: caine
  namespace: argocd
spec:
  description: Caine Project
  
  destinations:
  - namespace: caine-dev
    server: https://kubernetes.default.svc
  - namespace: caine-test
    server: https://kubernetes.default.svc
  
  sourceRepos:
  - https://github.com/kims/argocd-poc.git

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
