---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dev1-db-pass
  namespace: caine-dev
spec:
  encryptedData:
    password: AgCjcPMdTSahxIZ91Bab5nxDPLhSQ2scdkuw+CUu0OzQKbe3QVCom0lJ2cGBGOH+TYZBetX2zyvECOAWE6Qcudphnq9cbRto9uiWnZS1w7OhKWF0bQD7cKcFm1ZaKyj1jAu2sc2p87Kv46rcMN7F9FRJWFodE9Ur08WR7Hx6gIy6yS4+bUSXBdPtAH6UIFFRxbgA5QORSaTTYCsrqzpV0zlj5L+5bWc/jmTCeXNPCeWm1GscpHYEeejR2khfBpcVlqzPOOkVOTme1klj4RgqSj6JJEk3QRuzr1l8ycO029MRR4YAFMwd1gfyBIKQ8DaeXtJy3/6wiufVByRuyIr5BoQ8PKz2u+Eloaqx8q1wZ+tTuaWLtqXhNz5hHVQjyMFTEYdPNOMZc0KTLihiR3kulqOgLwDAqOsicTCkzWCuINXdhcYIBW27FUvPDLRWpAcajAE+qaqh9Mj+ppXQzJKyrakhiumSJFKInv3KJWa49nZSF5BLf1GILcYXGZ4sKi+0U6XhuGks2hZb+g0PI4JJoPNFUqZxLSzNDAp6okx+ua+QSu2L+KctBayShfehd6Kf6eurDLmm9IRt53yJ+XwodvbEovz70ZqUZlGSf6BVRRAr++KwUGfdEqw6byfCnQo7actA0nyx6iwbGpyFi0amsq0mbgdzarc3ncT1qcHwiIqt9zQaHQU3lsqRA3K48ZtfftkdszpW0pk=
    username: AgAtJKGZlSrSM8Z1HXIMocsHDCRcSwLopxaI5/QHyvmqDvRUDwDV80K7CIoDrZbU22IwihhbVUinIHyYHjvBpfyMnoRl30bF/IQLfkFGnQLMqiaZhFWWwzqGCbhf5tNw+sINpXp7Ov3RyoFFOMw6OXqId0EBpOtKeSNk6AR1MzSlrhKeRbbwnIgYFXtgec/W4E3UhI/c/tyYtbYYQqCvXvKvIkR9BvBdYw2r0bDqGt5LPziHf83Xi/bpkqfi8SEEINTZ7QNUCBs673rjxjrIxcSaaOQNOaTICs0IgMIPfZrB7J9xDEUVSNMm8YZDuW9BX1aPeQHlsy/MIC4oQluVMmGsJK6ZJFxaNMd6Kedg4/2OW7csp/Kzwc7Fo+AV7QRPXGpaJSSCS+VNypynIBz51Hk7v7Khxjl7VX8hrH3ryFWsHoAnOfTeDuBSKQ/NV/wGnN1N6MiCKdDrWRD3o/1T1lk5OBKTZ7viPfpEf5jZMvme3479rEdJAl88g0S+e0NXtX++MDQ5R6uroQbT+H3790dbayv8I+w+jq6MIQQ6ORT5U9J+G//MNPnzG2Ywr3D9b1KsqcY1OjSNdSeshisabvh20OEgLM2gKz8J4c+lkzfYnaxkag8W2ZtLJRafYrxYDspPheNA3I0YPv+A3Hg+JmptNAem7RUFIGMXrtx1a1hfobOP7drUkv0s+0h9JKY0YApr5dTP
  template:
    metadata:
      name: dev1-db-pass
      namespace: caine-dev
